 name: Test dependencies and requirements installation

 on:
  workflow_dispatch:
  push:
    paths:
      - 'docs/source/_static/install_dependencies.sh'
      - 'examples/install_requirements.py'
  pull_request:
      paths:
      - 'docs/source/_static/install_dependencies.sh'
      - 'examples/install_requirements.py'

 jobs:
   install_dependencies:
     runs-on: ubuntu-latest
     strategy:
       matrix:
          container_image: ["fedora:34", "fedora:35", "fedora:36", "ubuntu:18.04", "ubuntu:20.04", "ubuntu:22.04"]
     container:
       image: ${{ matrix.container_image }}
     steps:
       - uses: actions/checkout@v3
       - name: Install sudo
         if: startsWith(matrix.container_image, 'fedora') == true
         run: yum update -y && yum install -y sudo
       - name: Install sudo
         if: startsWith(matrix.container_image, 'ubuntu') == true
         run: apt-get update  -qq && apt-get -qq install sudo
       - name: Install dependencies
         run: |
           ln -snf /usr/share/zoneinfo/UTC /etc/localtime && echo UTC > /etc/timezone # Otherwise tzdata installer prompts for user input
           sed '/udevadm control --reload-rules && sudo udevadm trigger/d' docs/source/_static/install_dependencies.sh > tmp_script.sh # Doesn't work on docker
           bash tmp_script.sh
       - name: Install example requirements
         run: |
           python3 examples/install_requirements.py
